### ISSUE TITLE
Create a 0.3.3 release

### ISSUE THREAD

**Issue by dgmstuart** [varvet/tolken#77]
I've upgraded some dependencies so this should get a new release. Currently only @ramhoj is an owner on rubygems

**Comment by ramhoj** [comment]
@dgmstuart you should now have owner access to the ruby gem, I'd be happy to see a new release :). If you prefer to I can make the release myself but it might be a couple of days.

**Comment by dgmstuart** [comment]
Created! https://rubygems.org/gems/tolken/versions/0.3.3
